import type { Metadata } from "next";

import "./style.css";
import { handjet } from "./fonts";

export const metadata: Metadata = {
  title: "OBS clock overlay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={handjet.className}>{children}</body>
    </html>
  );
}
